version: '3.8'

services:
  signaling_server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: webrtc_signaling_server
    ports:
      - "8321:8321"
    networks:
      - app_network

networks:
  app_network:
    name: webrtc_signaling_server
    driver: bridge
