version: '3.8'

services:
  signaling_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webrtc_signaling_server
    ports:
      - "8888:8080"
    networks:
      - app_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

networks:
  app_network:
    name: webrtc_signaling_server
    driver: bridge
